// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CodeType.proto

package com.efun.game.protobuf.api;

public final class CodeTypeProto {
  private CodeTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息编码类型
   * </pre>
   *
   * Protobuf enum {@code protobuf.api.CodeType}
   */
  public enum CodeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * protobuf
     * </pre>
     *
     * <code>PROTOBUF = 0;</code>
     */
    PROTOBUF(0),
    /**
     * <pre>
     * json
     * </pre>
     *
     * <code>JSON = 1;</code>
     */
    JSON(1),
    ;

    /**
     * <pre>
     * protobuf
     * </pre>
     *
     * <code>PROTOBUF = 0;</code>
     */
    public static final int PROTOBUF_VALUE = 0;
    /**
     * <pre>
     * json
     * </pre>
     *
     * <code>JSON = 1;</code>
     */
    public static final int JSON_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CodeType valueOf(int value) {
      return forNumber(value);
    }

    public static CodeType forNumber(int value) {
      switch (value) {
        case 0: return PROTOBUF;
        case 1: return JSON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CodeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CodeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CodeType>() {
            public CodeType findValueByNumber(int number) {
              return CodeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.efun.game.protobuf.api.CodeTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CodeType[] VALUES = values();

    public static CodeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CodeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.api.CodeType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016CodeType.proto\022\014protobuf.api*\"\n\010CodeTy" +
      "pe\022\014\n\010PROTOBUF\020\000\022\010\n\004JSON\020\001B+\n\032com.efun.g" +
      "ame.protobuf.apiB\rCodeTypeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
