// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandId.proto

package com.efun.game.protobuf.api;

public final class CommandIdProto {
  private CommandIdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 握手请求消息，握手应答消息
   * 心跳请求消息，心跳应答消息
   * 业务请求消息，业务应答消息
   * 业务ONE WAY消息
   * 消息编码类型
   * </pre>
   *
   * Protobuf enum {@code protobuf.api.CommandId}
   */
  public enum CommandId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 握手请求消息
     * </pre>
     *
     * <code>HANDSHAKE_REQUEST = 0;</code>
     */
    HANDSHAKE_REQUEST(0),
    /**
     * <pre>
     * 握手响应消息
     * </pre>
     *
     * <code>HANDSHAKE_RESPONSE = 1;</code>
     */
    HANDSHAKE_RESPONSE(1),
    /**
     * <pre>
     * 心跳请求消息
     * </pre>
     *
     * <code>HEART_BEAT_REQUEST = 2;</code>
     */
    HEART_BEAT_REQUEST(2),
    /**
     * <pre>
     * 心跳响应消息
     * </pre>
     *
     * <code>HEART_BEAT_RESPONSE = 3;</code>
     */
    HEART_BEAT_RESPONSE(3),
    /**
     * <pre>
     * 用户认证请求消息
     * </pre>
     *
     * <code>SERVER_AUTH_REQUEST = 5000;</code>
     */
    SERVER_AUTH_REQUEST(5000),
    /**
     * <pre>
     * 用户认证响应消息
     * </pre>
     *
     * <code>SERVER_AUTH_RESPONSE = 5001;</code>
     */
    SERVER_AUTH_RESPONSE(5001),
    /**
     * <pre>
     * 用户注册请求消息
     * </pre>
     *
     * <code>USER_SIGN_UP_REQUEST = 10000;</code>
     */
    USER_SIGN_UP_REQUEST(10000),
    /**
     * <pre>
     * 用户注册应答消息
     * </pre>
     *
     * <code>USER_SIGN_UP_RESPONSE = 10001;</code>
     */
    USER_SIGN_UP_RESPONSE(10001),
    /**
     * <pre>
     * 用户登录请求消息
     * </pre>
     *
     * <code>USER_SIGN_IN_REQUEST = 10002;</code>
     */
    USER_SIGN_IN_REQUEST(10002),
    /**
     * <pre>
     * 用户登录应答消息
     * </pre>
     *
     * <code>USER_SIGN_IN_RESPONSE = 10003;</code>
     */
    USER_SIGN_IN_RESPONSE(10003),
    ;

    /**
     * <pre>
     * 握手请求消息
     * </pre>
     *
     * <code>HANDSHAKE_REQUEST = 0;</code>
     */
    public static final int HANDSHAKE_REQUEST_VALUE = 0;
    /**
     * <pre>
     * 握手响应消息
     * </pre>
     *
     * <code>HANDSHAKE_RESPONSE = 1;</code>
     */
    public static final int HANDSHAKE_RESPONSE_VALUE = 1;
    /**
     * <pre>
     * 心跳请求消息
     * </pre>
     *
     * <code>HEART_BEAT_REQUEST = 2;</code>
     */
    public static final int HEART_BEAT_REQUEST_VALUE = 2;
    /**
     * <pre>
     * 心跳响应消息
     * </pre>
     *
     * <code>HEART_BEAT_RESPONSE = 3;</code>
     */
    public static final int HEART_BEAT_RESPONSE_VALUE = 3;
    /**
     * <pre>
     * 用户认证请求消息
     * </pre>
     *
     * <code>SERVER_AUTH_REQUEST = 5000;</code>
     */
    public static final int SERVER_AUTH_REQUEST_VALUE = 5000;
    /**
     * <pre>
     * 用户认证响应消息
     * </pre>
     *
     * <code>SERVER_AUTH_RESPONSE = 5001;</code>
     */
    public static final int SERVER_AUTH_RESPONSE_VALUE = 5001;
    /**
     * <pre>
     * 用户注册请求消息
     * </pre>
     *
     * <code>USER_SIGN_UP_REQUEST = 10000;</code>
     */
    public static final int USER_SIGN_UP_REQUEST_VALUE = 10000;
    /**
     * <pre>
     * 用户注册应答消息
     * </pre>
     *
     * <code>USER_SIGN_UP_RESPONSE = 10001;</code>
     */
    public static final int USER_SIGN_UP_RESPONSE_VALUE = 10001;
    /**
     * <pre>
     * 用户登录请求消息
     * </pre>
     *
     * <code>USER_SIGN_IN_REQUEST = 10002;</code>
     */
    public static final int USER_SIGN_IN_REQUEST_VALUE = 10002;
    /**
     * <pre>
     * 用户登录应答消息
     * </pre>
     *
     * <code>USER_SIGN_IN_RESPONSE = 10003;</code>
     */
    public static final int USER_SIGN_IN_RESPONSE_VALUE = 10003;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandId valueOf(int value) {
      return forNumber(value);
    }

    public static CommandId forNumber(int value) {
      switch (value) {
        case 0: return HANDSHAKE_REQUEST;
        case 1: return HANDSHAKE_RESPONSE;
        case 2: return HEART_BEAT_REQUEST;
        case 3: return HEART_BEAT_RESPONSE;
        case 5000: return SERVER_AUTH_REQUEST;
        case 5001: return SERVER_AUTH_RESPONSE;
        case 10000: return USER_SIGN_UP_REQUEST;
        case 10001: return USER_SIGN_UP_RESPONSE;
        case 10002: return USER_SIGN_IN_REQUEST;
        case 10003: return USER_SIGN_IN_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandId>() {
            public CommandId findValueByNumber(int number) {
              return CommandId.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.efun.game.protobuf.api.CommandIdProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandId[] VALUES = values();

    public static CommandId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.api.CommandId)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CommandId.proto\022\014protobuf.api*\216\002\n\tComm" +
      "andId\022\025\n\021HANDSHAKE_REQUEST\020\000\022\026\n\022HANDSHAK" +
      "E_RESPONSE\020\001\022\026\n\022HEART_BEAT_REQUEST\020\002\022\027\n\023" +
      "HEART_BEAT_RESPONSE\020\003\022\030\n\023SERVER_AUTH_REQ" +
      "UEST\020\210\'\022\031\n\024SERVER_AUTH_RESPONSE\020\211\'\022\031\n\024US" +
      "ER_SIGN_UP_REQUEST\020\220N\022\032\n\025USER_SIGN_UP_RE" +
      "SPONSE\020\221N\022\031\n\024USER_SIGN_IN_REQUEST\020\222N\022\032\n\025" +
      "USER_SIGN_IN_RESPONSE\020\223NB,\n\032com.efun.gam" +
      "e.protobuf.apiB\016CommandIdProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
