// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EncryptionType.proto

package com.efun.game.protobuf.api;

public final class EncryptionTypeProto {
  private EncryptionTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息加解密类型
   * </pre>
   *
   * Protobuf enum {@code protobuf.api.EncryptionType}
   */
  public enum EncryptionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 0-不加密
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    NONE(0),
    ;

    /**
     * <pre>
     * 0-不加密
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EncryptionType valueOf(int value) {
      return forNumber(value);
    }

    public static EncryptionType forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EncryptionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EncryptionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EncryptionType>() {
            public EncryptionType findValueByNumber(int number) {
              return EncryptionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.efun.game.protobuf.api.EncryptionTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final EncryptionType[] VALUES = values();

    public static EncryptionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EncryptionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.api.EncryptionType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024EncryptionType.proto\022\014protobuf.api*\032\n\016" +
      "EncryptionType\022\010\n\004NONE\020\000B1\n\032com.efun.gam" +
      "e.protobuf.apiB\023EncryptionTypeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
