// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

package com.efun.game.protobuf.api;

public final class HeaderProto {
  private HeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
     * </pre>
     *
     * <code>required fixed32 crcCode = 1;</code>
     */
    boolean hasCrcCode();
    /**
     * <pre>
     * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
     * </pre>
     *
     * <code>required fixed32 crcCode = 1;</code>
     */
    int getCrcCode();

    /**
     * <pre>
     * id: 会话Id内唯一
     * </pre>
     *
     * <code>required fixed64 id = 2;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * id: 会话Id内唯一
     * </pre>
     *
     * <code>required fixed64 id = 2;</code>
     */
    long getId();

    /**
     * <pre>
     * 业务Id：全局唯一
     * </pre>
     *
     * <code>required .protobuf.api.CommandId commandId = 3;</code>
     */
    boolean hasCommandId();
    /**
     * <pre>
     * 业务Id：全局唯一
     * </pre>
     *
     * <code>required .protobuf.api.CommandId commandId = 3;</code>
     */
    com.efun.game.protobuf.api.CommandIdProto.CommandId getCommandId();

    /**
     * <pre>
     * 会话Id，集群全局唯一
     * </pre>
     *
     * <code>required fixed32 sessionId = 4;</code>
     */
    boolean hasSessionId();
    /**
     * <pre>
     * 会话Id，集群全局唯一
     * </pre>
     *
     * <code>required fixed32 sessionId = 4;</code>
     */
    int getSessionId();

    /**
     * <pre>
     * 加密类型: 0-不加密
     * </pre>
     *
     * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
     */
    boolean hasEncryptionType();
    /**
     * <pre>
     * 加密类型: 0-不加密
     * </pre>
     *
     * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
     */
    com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType getEncryptionType();

    /**
     * <pre>
     * 编解码类型: 0-protobuf; 1-json 
     * </pre>
     *
     * <code>required .protobuf.api.CodeType codeType = 6;</code>
     */
    boolean hasCodeType();
    /**
     * <pre>
     * 编解码类型: 0-protobuf; 1-json 
     * </pre>
     *
     * <code>required .protobuf.api.CodeType codeType = 6;</code>
     */
    com.efun.game.protobuf.api.CodeTypeProto.CodeType getCodeType();
  }
  /**
   * Protobuf type {@code protobuf.api.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.api.Header)
      HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      crcCode_ = 0;
      id_ = 0L;
      commandId_ = 0;
      sessionId_ = 0;
      encryptionType_ = 0;
      codeType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              crcCode_ = input.readFixed32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              id_ = input.readFixed64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.api.CommandIdProto.CommandId value = com.efun.game.protobuf.api.CommandIdProto.CommandId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                commandId_ = rawValue;
              }
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              sessionId_ = input.readFixed32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType value = com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                encryptionType_ = rawValue;
              }
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.api.CodeTypeProto.CodeType value = com.efun.game.protobuf.api.CodeTypeProto.CodeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                codeType_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.efun.game.protobuf.api.HeaderProto.internal_static_protobuf_api_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.efun.game.protobuf.api.HeaderProto.internal_static_protobuf_api_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.efun.game.protobuf.api.HeaderProto.Header.class, com.efun.game.protobuf.api.HeaderProto.Header.Builder.class);
    }

    private int bitField0_;
    public static final int CRCCODE_FIELD_NUMBER = 1;
    private int crcCode_;
    /**
     * <pre>
     * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
     * </pre>
     *
     * <code>required fixed32 crcCode = 1;</code>
     */
    public boolean hasCrcCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
     * </pre>
     *
     * <code>required fixed32 crcCode = 1;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     * id: 会话Id内唯一
     * </pre>
     *
     * <code>required fixed64 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * id: 会话Id内唯一
     * </pre>
     *
     * <code>required fixed64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int COMMANDID_FIELD_NUMBER = 3;
    private int commandId_;
    /**
     * <pre>
     * 业务Id：全局唯一
     * </pre>
     *
     * <code>required .protobuf.api.CommandId commandId = 3;</code>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 业务Id：全局唯一
     * </pre>
     *
     * <code>required .protobuf.api.CommandId commandId = 3;</code>
     */
    public com.efun.game.protobuf.api.CommandIdProto.CommandId getCommandId() {
      com.efun.game.protobuf.api.CommandIdProto.CommandId result = com.efun.game.protobuf.api.CommandIdProto.CommandId.valueOf(commandId_);
      return result == null ? com.efun.game.protobuf.api.CommandIdProto.CommandId.HANDSHAKE_REQUEST : result;
    }

    public static final int SESSIONID_FIELD_NUMBER = 4;
    private int sessionId_;
    /**
     * <pre>
     * 会话Id，集群全局唯一
     * </pre>
     *
     * <code>required fixed32 sessionId = 4;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 会话Id，集群全局唯一
     * </pre>
     *
     * <code>required fixed32 sessionId = 4;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int ENCRYPTIONTYPE_FIELD_NUMBER = 5;
    private int encryptionType_;
    /**
     * <pre>
     * 加密类型: 0-不加密
     * </pre>
     *
     * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
     */
    public boolean hasEncryptionType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 加密类型: 0-不加密
     * </pre>
     *
     * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
     */
    public com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType getEncryptionType() {
      com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType result = com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType.valueOf(encryptionType_);
      return result == null ? com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType.NONE : result;
    }

    public static final int CODETYPE_FIELD_NUMBER = 6;
    private int codeType_;
    /**
     * <pre>
     * 编解码类型: 0-protobuf; 1-json 
     * </pre>
     *
     * <code>required .protobuf.api.CodeType codeType = 6;</code>
     */
    public boolean hasCodeType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 编解码类型: 0-protobuf; 1-json 
     * </pre>
     *
     * <code>required .protobuf.api.CodeType codeType = 6;</code>
     */
    public com.efun.game.protobuf.api.CodeTypeProto.CodeType getCodeType() {
      com.efun.game.protobuf.api.CodeTypeProto.CodeType result = com.efun.game.protobuf.api.CodeTypeProto.CodeType.valueOf(codeType_);
      return result == null ? com.efun.game.protobuf.api.CodeTypeProto.CodeType.PROTOBUF : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCrcCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommandId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCodeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, crcCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, commandId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed32(4, sessionId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, encryptionType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, codeType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, crcCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, commandId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, sessionId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, encryptionType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, codeType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.efun.game.protobuf.api.HeaderProto.Header)) {
        return super.equals(obj);
      }
      com.efun.game.protobuf.api.HeaderProto.Header other = (com.efun.game.protobuf.api.HeaderProto.Header) obj;

      boolean result = true;
      result = result && (hasCrcCode() == other.hasCrcCode());
      if (hasCrcCode()) {
        result = result && (getCrcCode()
            == other.getCrcCode());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasCommandId() == other.hasCommandId());
      if (hasCommandId()) {
        result = result && commandId_ == other.commandId_;
      }
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && (getSessionId()
            == other.getSessionId());
      }
      result = result && (hasEncryptionType() == other.hasEncryptionType());
      if (hasEncryptionType()) {
        result = result && encryptionType_ == other.encryptionType_;
      }
      result = result && (hasCodeType() == other.hasCodeType());
      if (hasCodeType()) {
        result = result && codeType_ == other.codeType_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCrcCode()) {
        hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCrcCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasCommandId()) {
        hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
        hash = (53 * hash) + commandId_;
      }
      if (hasSessionId()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId();
      }
      if (hasEncryptionType()) {
        hash = (37 * hash) + ENCRYPTIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + encryptionType_;
      }
      if (hasCodeType()) {
        hash = (37 * hash) + CODETYPE_FIELD_NUMBER;
        hash = (53 * hash) + codeType_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.api.HeaderProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.efun.game.protobuf.api.HeaderProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.Header)
        com.efun.game.protobuf.api.HeaderProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.efun.game.protobuf.api.HeaderProto.internal_static_protobuf_api_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.efun.game.protobuf.api.HeaderProto.internal_static_protobuf_api_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.efun.game.protobuf.api.HeaderProto.Header.class, com.efun.game.protobuf.api.HeaderProto.Header.Builder.class);
      }

      // Construct using com.efun.game.protobuf.api.HeaderProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        crcCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        commandId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        encryptionType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        codeType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.efun.game.protobuf.api.HeaderProto.internal_static_protobuf_api_Header_descriptor;
      }

      public com.efun.game.protobuf.api.HeaderProto.Header getDefaultInstanceForType() {
        return com.efun.game.protobuf.api.HeaderProto.Header.getDefaultInstance();
      }

      public com.efun.game.protobuf.api.HeaderProto.Header build() {
        com.efun.game.protobuf.api.HeaderProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.efun.game.protobuf.api.HeaderProto.Header buildPartial() {
        com.efun.game.protobuf.api.HeaderProto.Header result = new com.efun.game.protobuf.api.HeaderProto.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.crcCode_ = crcCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.commandId_ = commandId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.encryptionType_ = encryptionType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.codeType_ = codeType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.efun.game.protobuf.api.HeaderProto.Header) {
          return mergeFrom((com.efun.game.protobuf.api.HeaderProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.efun.game.protobuf.api.HeaderProto.Header other) {
        if (other == com.efun.game.protobuf.api.HeaderProto.Header.getDefaultInstance()) return this;
        if (other.hasCrcCode()) {
          setCrcCode(other.getCrcCode());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCommandId()) {
          setCommandId(other.getCommandId());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasEncryptionType()) {
          setEncryptionType(other.getEncryptionType());
        }
        if (other.hasCodeType()) {
          setCodeType(other.getCodeType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCrcCode()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasCommandId()) {
          return false;
        }
        if (!hasSessionId()) {
          return false;
        }
        if (!hasEncryptionType()) {
          return false;
        }
        if (!hasCodeType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.efun.game.protobuf.api.HeaderProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.efun.game.protobuf.api.HeaderProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int crcCode_ ;
      /**
       * <pre>
       * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
       * </pre>
       *
       * <code>required fixed32 crcCode = 1;</code>
       */
      public boolean hasCrcCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
       * </pre>
       *
       * <code>required fixed32 crcCode = 1;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <pre>
       * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
       * </pre>
       *
       * <code>required fixed32 crcCode = 1;</code>
       */
      public Builder setCrcCode(int value) {
        bitField0_ |= 0x00000001;
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息校验码：固定值+主版本号+次版本号, 2个字节+1个字节+1个字节
       * </pre>
       *
       * <code>required fixed32 crcCode = 1;</code>
       */
      public Builder clearCrcCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        crcCode_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * id: 会话Id内唯一
       * </pre>
       *
       * <code>required fixed64 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * id: 会话Id内唯一
       * </pre>
       *
       * <code>required fixed64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * id: 会话Id内唯一
       * </pre>
       *
       * <code>required fixed64 id = 2;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * id: 会话Id内唯一
       * </pre>
       *
       * <code>required fixed64 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int commandId_ = 0;
      /**
       * <pre>
       * 业务Id：全局唯一
       * </pre>
       *
       * <code>required .protobuf.api.CommandId commandId = 3;</code>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 业务Id：全局唯一
       * </pre>
       *
       * <code>required .protobuf.api.CommandId commandId = 3;</code>
       */
      public com.efun.game.protobuf.api.CommandIdProto.CommandId getCommandId() {
        com.efun.game.protobuf.api.CommandIdProto.CommandId result = com.efun.game.protobuf.api.CommandIdProto.CommandId.valueOf(commandId_);
        return result == null ? com.efun.game.protobuf.api.CommandIdProto.CommandId.HANDSHAKE_REQUEST : result;
      }
      /**
       * <pre>
       * 业务Id：全局唯一
       * </pre>
       *
       * <code>required .protobuf.api.CommandId commandId = 3;</code>
       */
      public Builder setCommandId(com.efun.game.protobuf.api.CommandIdProto.CommandId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        commandId_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 业务Id：全局唯一
       * </pre>
       *
       * <code>required .protobuf.api.CommandId commandId = 3;</code>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        commandId_ = 0;
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <pre>
       * 会话Id，集群全局唯一
       * </pre>
       *
       * <code>required fixed32 sessionId = 4;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 会话Id，集群全局唯一
       * </pre>
       *
       * <code>required fixed32 sessionId = 4;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <pre>
       * 会话Id，集群全局唯一
       * </pre>
       *
       * <code>required fixed32 sessionId = 4;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000008;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话Id，集群全局唯一
       * </pre>
       *
       * <code>required fixed32 sessionId = 4;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private int encryptionType_ = 0;
      /**
       * <pre>
       * 加密类型: 0-不加密
       * </pre>
       *
       * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
       */
      public boolean hasEncryptionType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 加密类型: 0-不加密
       * </pre>
       *
       * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
       */
      public com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType getEncryptionType() {
        com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType result = com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType.valueOf(encryptionType_);
        return result == null ? com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType.NONE : result;
      }
      /**
       * <pre>
       * 加密类型: 0-不加密
       * </pre>
       *
       * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
       */
      public Builder setEncryptionType(com.efun.game.protobuf.api.EncryptionTypeProto.EncryptionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        encryptionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 加密类型: 0-不加密
       * </pre>
       *
       * <code>required .protobuf.api.EncryptionType encryptionType = 5;</code>
       */
      public Builder clearEncryptionType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        encryptionType_ = 0;
        onChanged();
        return this;
      }

      private int codeType_ = 0;
      /**
       * <pre>
       * 编解码类型: 0-protobuf; 1-json 
       * </pre>
       *
       * <code>required .protobuf.api.CodeType codeType = 6;</code>
       */
      public boolean hasCodeType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 编解码类型: 0-protobuf; 1-json 
       * </pre>
       *
       * <code>required .protobuf.api.CodeType codeType = 6;</code>
       */
      public com.efun.game.protobuf.api.CodeTypeProto.CodeType getCodeType() {
        com.efun.game.protobuf.api.CodeTypeProto.CodeType result = com.efun.game.protobuf.api.CodeTypeProto.CodeType.valueOf(codeType_);
        return result == null ? com.efun.game.protobuf.api.CodeTypeProto.CodeType.PROTOBUF : result;
      }
      /**
       * <pre>
       * 编解码类型: 0-protobuf; 1-json 
       * </pre>
       *
       * <code>required .protobuf.api.CodeType codeType = 6;</code>
       */
      public Builder setCodeType(com.efun.game.protobuf.api.CodeTypeProto.CodeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        codeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 编解码类型: 0-protobuf; 1-json 
       * </pre>
       *
       * <code>required .protobuf.api.CodeType codeType = 6;</code>
       */
      public Builder clearCodeType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        codeType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.api.Header)
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.Header)
    private static final com.efun.game.protobuf.api.HeaderProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.efun.game.protobuf.api.HeaderProto.Header();
    }

    public static com.efun.game.protobuf.api.HeaderProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    public com.efun.game.protobuf.api.HeaderProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_api_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Header.proto\022\014protobuf.api\032\017CommandId." +
      "proto\032\024EncryptionType.proto\032\016CodeType.pr" +
      "oto\"\304\001\n\006Header\022\017\n\007crcCode\030\001 \002(\007\022\n\n\002id\030\002 " +
      "\002(\006\022*\n\tcommandId\030\003 \002(\0162\027.protobuf.api.Co" +
      "mmandId\022\021\n\tsessionId\030\004 \002(\007\0224\n\016encryption" +
      "Type\030\005 \002(\0162\034.protobuf.api.EncryptionType" +
      "\022(\n\010codeType\030\006 \002(\0162\026.protobuf.api.CodeTy" +
      "peB)\n\032com.efun.game.protobuf.apiB\013Header" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.efun.game.protobuf.api.CommandIdProto.getDescriptor(),
          com.efun.game.protobuf.api.EncryptionTypeProto.getDescriptor(),
          com.efun.game.protobuf.api.CodeTypeProto.getDescriptor(),
        }, assigner);
    internal_static_protobuf_api_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_api_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_api_Header_descriptor,
        new java.lang.String[] { "CrcCode", "Id", "CommandId", "SessionId", "EncryptionType", "CodeType", });
    com.efun.game.protobuf.api.CommandIdProto.getDescriptor();
    com.efun.game.protobuf.api.EncryptionTypeProto.getDescriptor();
    com.efun.game.protobuf.api.CodeTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
