// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/UserSignUpReq.proto

package com.efun.game.protobuf.app.user;

public final class UserSignUpReqProto {
  private UserSignUpReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserSignUpReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.app.user.UserSignUpReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户类型
     * </pre>
     *
     * <code>required .protobuf.app.UserType userType = 1;</code>
     */
    boolean hasUserType();
    /**
     * <pre>
     * 用户类型
     * </pre>
     *
     * <code>required .protobuf.app.UserType userType = 1;</code>
     */
    com.efun.game.protobuf.app.EnumsProto.UserType getUserType();

    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>required string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>required string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>required string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>required string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <pre>
     * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 4;</code>
     */
    boolean hasAppType();
    /**
     * <pre>
     * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 4;</code>
     */
    com.efun.game.protobuf.app.EnumsProto.AppType getAppType();

    /**
     * <pre>
     * 注册ip
     * </pre>
     *
     * <code>required string regIp = 5;</code>
     */
    boolean hasRegIp();
    /**
     * <pre>
     * 注册ip
     * </pre>
     *
     * <code>required string regIp = 5;</code>
     */
    java.lang.String getRegIp();
    /**
     * <pre>
     * 注册ip
     * </pre>
     *
     * <code>required string regIp = 5;</code>
     */
    com.google.protobuf.ByteString
        getRegIpBytes();
  }
  /**
   * Protobuf type {@code protobuf.app.user.UserSignUpReq}
   */
  public  static final class UserSignUpReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.app.user.UserSignUpReq)
      UserSignUpReqOrBuilder {
    // Use UserSignUpReq.newBuilder() to construct.
    private UserSignUpReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserSignUpReq() {
      userType_ = 1;
      userName_ = "";
      password_ = "";
      appType_ = 0;
      regIp_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserSignUpReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.app.EnumsProto.UserType value = com.efun.game.protobuf.app.EnumsProto.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                userType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              password_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.app.EnumsProto.AppType value = com.efun.game.protobuf.app.EnumsProto.AppType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                appType_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              regIp_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.efun.game.protobuf.app.user.UserSignUpReqProto.internal_static_protobuf_app_user_UserSignUpReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.efun.game.protobuf.app.user.UserSignUpReqProto.internal_static_protobuf_app_user_UserSignUpReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.class, com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.Builder.class);
    }

    private int bitField0_;
    public static final int USERTYPE_FIELD_NUMBER = 1;
    private int userType_;
    /**
     * <pre>
     * 用户类型
     * </pre>
     *
     * <code>required .protobuf.app.UserType userType = 1;</code>
     */
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 用户类型
     * </pre>
     *
     * <code>required .protobuf.app.UserType userType = 1;</code>
     */
    public com.efun.game.protobuf.app.EnumsProto.UserType getUserType() {
      com.efun.game.protobuf.app.EnumsProto.UserType result = com.efun.game.protobuf.app.EnumsProto.UserType.valueOf(userType_);
      return result == null ? com.efun.game.protobuf.app.EnumsProto.UserType.USER_NAME : result;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>required string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>required string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>required string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>required string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPTYPE_FIELD_NUMBER = 4;
    private int appType_;
    /**
     * <pre>
     * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 4;</code>
     */
    public boolean hasAppType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 4;</code>
     */
    public com.efun.game.protobuf.app.EnumsProto.AppType getAppType() {
      com.efun.game.protobuf.app.EnumsProto.AppType result = com.efun.game.protobuf.app.EnumsProto.AppType.valueOf(appType_);
      return result == null ? com.efun.game.protobuf.app.EnumsProto.AppType.APP_UNKNOWN : result;
    }

    public static final int REGIP_FIELD_NUMBER = 5;
    private volatile java.lang.Object regIp_;
    /**
     * <pre>
     * 注册ip
     * </pre>
     *
     * <code>required string regIp = 5;</code>
     */
    public boolean hasRegIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 注册ip
     * </pre>
     *
     * <code>required string regIp = 5;</code>
     */
    public java.lang.String getRegIp() {
      java.lang.Object ref = regIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          regIp_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 注册ip
     * </pre>
     *
     * <code>required string regIp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRegIpBytes() {
      java.lang.Object ref = regIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRegIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, userType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, appType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, regIp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, userType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, appType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, regIp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq)) {
        return super.equals(obj);
      }
      com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq other = (com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq) obj;

      boolean result = true;
      result = result && (hasUserType() == other.hasUserType());
      if (hasUserType()) {
        result = result && userType_ == other.userType_;
      }
      result = result && (hasUserName() == other.hasUserName());
      if (hasUserName()) {
        result = result && getUserName()
            .equals(other.getUserName());
      }
      result = result && (hasPassword() == other.hasPassword());
      if (hasPassword()) {
        result = result && getPassword()
            .equals(other.getPassword());
      }
      result = result && (hasAppType() == other.hasAppType());
      if (hasAppType()) {
        result = result && appType_ == other.appType_;
      }
      result = result && (hasRegIp() == other.hasRegIp());
      if (hasRegIp()) {
        result = result && getRegIp()
            .equals(other.getRegIp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserType()) {
        hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + userType_;
      }
      if (hasUserName()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      if (hasAppType()) {
        hash = (37 * hash) + APPTYPE_FIELD_NUMBER;
        hash = (53 * hash) + appType_;
      }
      if (hasRegIp()) {
        hash = (37 * hash) + REGIP_FIELD_NUMBER;
        hash = (53 * hash) + getRegIp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.app.user.UserSignUpReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.app.user.UserSignUpReq)
        com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.efun.game.protobuf.app.user.UserSignUpReqProto.internal_static_protobuf_app_user_UserSignUpReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.efun.game.protobuf.app.user.UserSignUpReqProto.internal_static_protobuf_app_user_UserSignUpReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.class, com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.Builder.class);
      }

      // Construct using com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        appType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        regIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.efun.game.protobuf.app.user.UserSignUpReqProto.internal_static_protobuf_app_user_UserSignUpReq_descriptor;
      }

      public com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq getDefaultInstanceForType() {
        return com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.getDefaultInstance();
      }

      public com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq build() {
        com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq buildPartial() {
        com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq result = new com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userType_ = userType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appType_ = appType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.regIp_ = regIp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq) {
          return mergeFrom((com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq other) {
        if (other == com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq.getDefaultInstance()) return this;
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasAppType()) {
          setAppType(other.getAppType());
        }
        if (other.hasRegIp()) {
          bitField0_ |= 0x00000010;
          regIp_ = other.regIp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserType()) {
          return false;
        }
        if (!hasUserName()) {
          return false;
        }
        if (!hasPassword()) {
          return false;
        }
        if (!hasAppType()) {
          return false;
        }
        if (!hasRegIp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userType_ = 1;
      /**
       * <pre>
       * 用户类型
       * </pre>
       *
       * <code>required .protobuf.app.UserType userType = 1;</code>
       */
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 用户类型
       * </pre>
       *
       * <code>required .protobuf.app.UserType userType = 1;</code>
       */
      public com.efun.game.protobuf.app.EnumsProto.UserType getUserType() {
        com.efun.game.protobuf.app.EnumsProto.UserType result = com.efun.game.protobuf.app.EnumsProto.UserType.valueOf(userType_);
        return result == null ? com.efun.game.protobuf.app.EnumsProto.UserType.USER_NAME : result;
      }
      /**
       * <pre>
       * 用户类型
       * </pre>
       *
       * <code>required .protobuf.app.UserType userType = 1;</code>
       */
      public Builder setUserType(com.efun.game.protobuf.app.EnumsProto.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        userType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户类型
       * </pre>
       *
       * <code>required .protobuf.app.UserType userType = 1;</code>
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>required string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>required string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>required string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>required string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>required string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>required string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>required string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      private int appType_ = 0;
      /**
       * <pre>
       * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 4;</code>
       */
      public boolean hasAppType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 4;</code>
       */
      public com.efun.game.protobuf.app.EnumsProto.AppType getAppType() {
        com.efun.game.protobuf.app.EnumsProto.AppType result = com.efun.game.protobuf.app.EnumsProto.AppType.valueOf(appType_);
        return result == null ? com.efun.game.protobuf.app.EnumsProto.AppType.APP_UNKNOWN : result;
      }
      /**
       * <pre>
       * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 4;</code>
       */
      public Builder setAppType(com.efun.game.protobuf.app.EnumsProto.AppType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        appType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * app类型: 0-未知; 1-Web; 2-IOS; 3-Andriod
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 4;</code>
       */
      public Builder clearAppType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object regIp_ = "";
      /**
       * <pre>
       * 注册ip
       * </pre>
       *
       * <code>required string regIp = 5;</code>
       */
      public boolean hasRegIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 注册ip
       * </pre>
       *
       * <code>required string regIp = 5;</code>
       */
      public java.lang.String getRegIp() {
        java.lang.Object ref = regIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            regIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 注册ip
       * </pre>
       *
       * <code>required string regIp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRegIpBytes() {
        java.lang.Object ref = regIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 注册ip
       * </pre>
       *
       * <code>required string regIp = 5;</code>
       */
      public Builder setRegIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        regIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 注册ip
       * </pre>
       *
       * <code>required string regIp = 5;</code>
       */
      public Builder clearRegIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        regIp_ = getDefaultInstance().getRegIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 注册ip
       * </pre>
       *
       * <code>required string regIp = 5;</code>
       */
      public Builder setRegIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        regIp_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.app.user.UserSignUpReq)
    }

    // @@protoc_insertion_point(class_scope:protobuf.app.user.UserSignUpReq)
    private static final com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq();
    }

    public static com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserSignUpReq>
        PARSER = new com.google.protobuf.AbstractParser<UserSignUpReq>() {
      public UserSignUpReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserSignUpReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserSignUpReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserSignUpReq> getParserForType() {
      return PARSER;
    }

    public com.efun.game.protobuf.app.user.UserSignUpReqProto.UserSignUpReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_app_user_UserSignUpReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_app_user_UserSignUpReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030user/UserSignUpReq.proto\022\021protobuf.app" +
      ".user\032\013Enums.proto\"\224\001\n\rUserSignUpReq\022(\n\010" +
      "userType\030\001 \002(\0162\026.protobuf.app.UserType\022\020" +
      "\n\010userName\030\002 \002(\t\022\020\n\010password\030\003 \002(\t\022&\n\007ap" +
      "pType\030\004 \002(\0162\025.protobuf.app.AppType\022\r\n\005re" +
      "gIp\030\005 \002(\tB5\n\037com.efun.game.protobuf.app." +
      "userB\022UserSignUpReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.efun.game.protobuf.app.EnumsProto.getDescriptor(),
        }, assigner);
    internal_static_protobuf_app_user_UserSignUpReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_app_user_UserSignUpReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_app_user_UserSignUpReq_descriptor,
        new java.lang.String[] { "UserType", "UserName", "Password", "AppType", "RegIp", });
    com.efun.game.protobuf.app.EnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
