// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/UserSignInResp.proto

package com.efun.game.protobuf.app.user;

public final class UserSingInRespProto {
  private UserSingInRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserSignInRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.app.user.UserSignInResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 处理结果
     * </pre>
     *
     * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
     */
    boolean hasBaseResp();
    /**
     * <pre>
     * 处理结果
     * </pre>
     *
     * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
     */
    com.efun.game.protobuf.app.BaseRespProto.BaseResp getBaseResp();
    /**
     * <pre>
     * 处理结果
     * </pre>
     *
     * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
     */
    com.efun.game.protobuf.app.BaseRespProto.BaseRespOrBuilder getBaseRespOrBuilder();

    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>optional fixed64 uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>optional fixed64 uid = 2;</code>
     */
    long getUid();

    /**
     * <code>optional fixed64 sessionId = 3;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional fixed64 sessionId = 3;</code>
     */
    long getSessionId();

    /**
     * <pre>
     * 登录ip
     * </pre>
     *
     * <code>optional string loginIp = 4;</code>
     */
    boolean hasLoginIp();
    /**
     * <pre>
     * 登录ip
     * </pre>
     *
     * <code>optional string loginIp = 4;</code>
     */
    java.lang.String getLoginIp();
    /**
     * <pre>
     * 登录ip
     * </pre>
     *
     * <code>optional string loginIp = 4;</code>
     */
    com.google.protobuf.ByteString
        getLoginIpBytes();

    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string nickName = 5;</code>
     */
    boolean hasNickName();
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string nickName = 5;</code>
     */
    java.lang.String getNickName();
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string nickName = 5;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <pre>
     * 头像地址
     * </pre>
     *
     * <code>optional string headPictureUrl = 6;</code>
     */
    boolean hasHeadPictureUrl();
    /**
     * <pre>
     * 头像地址
     * </pre>
     *
     * <code>optional string headPictureUrl = 6;</code>
     */
    java.lang.String getHeadPictureUrl();
    /**
     * <pre>
     * 头像地址
     * </pre>
     *
     * <code>optional string headPictureUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getHeadPictureUrlBytes();

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional string gender = 7;</code>
     */
    boolean hasGender();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional string gender = 7;</code>
     */
    java.lang.String getGender();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional string gender = 7;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();
  }
  /**
   * Protobuf type {@code protobuf.app.user.UserSignInResp}
   */
  public  static final class UserSignInResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.app.user.UserSignInResp)
      UserSignInRespOrBuilder {
    // Use UserSignInResp.newBuilder() to construct.
    private UserSignInResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserSignInResp() {
      uid_ = 0L;
      sessionId_ = 0L;
      loginIp_ = "";
      nickName_ = "";
      headPictureUrl_ = "";
      gender_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserSignInResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.efun.game.protobuf.app.BaseRespProto.BaseResp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = baseResp_.toBuilder();
              }
              baseResp_ = input.readMessage(com.efun.game.protobuf.app.BaseRespProto.BaseResp.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResp_);
                baseResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              uid_ = input.readFixed64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              sessionId_ = input.readFixed64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              loginIp_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              nickName_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              headPictureUrl_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              gender_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.efun.game.protobuf.app.user.UserSingInRespProto.internal_static_protobuf_app_user_UserSignInResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.efun.game.protobuf.app.user.UserSingInRespProto.internal_static_protobuf_app_user_UserSignInResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.class, com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.Builder.class);
    }

    private int bitField0_;
    public static final int BASERESP_FIELD_NUMBER = 1;
    private com.efun.game.protobuf.app.BaseRespProto.BaseResp baseResp_;
    /**
     * <pre>
     * 处理结果
     * </pre>
     *
     * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
     */
    public boolean hasBaseResp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 处理结果
     * </pre>
     *
     * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
     */
    public com.efun.game.protobuf.app.BaseRespProto.BaseResp getBaseResp() {
      return baseResp_ == null ? com.efun.game.protobuf.app.BaseRespProto.BaseResp.getDefaultInstance() : baseResp_;
    }
    /**
     * <pre>
     * 处理结果
     * </pre>
     *
     * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
     */
    public com.efun.game.protobuf.app.BaseRespProto.BaseRespOrBuilder getBaseRespOrBuilder() {
      return baseResp_ == null ? com.efun.game.protobuf.app.BaseRespProto.BaseResp.getDefaultInstance() : baseResp_;
    }

    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>optional fixed64 uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>optional fixed64 uid = 2;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionId_;
    /**
     * <code>optional fixed64 sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional fixed64 sessionId = 3;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int LOGINIP_FIELD_NUMBER = 4;
    private volatile java.lang.Object loginIp_;
    /**
     * <pre>
     * 登录ip
     * </pre>
     *
     * <code>optional string loginIp = 4;</code>
     */
    public boolean hasLoginIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 登录ip
     * </pre>
     *
     * <code>optional string loginIp = 4;</code>
     */
    public java.lang.String getLoginIp() {
      java.lang.Object ref = loginIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginIp_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 登录ip
     * </pre>
     *
     * <code>optional string loginIp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoginIpBytes() {
      java.lang.Object ref = loginIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object nickName_;
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string nickName = 5;</code>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string nickName = 5;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>optional string nickName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADPICTUREURL_FIELD_NUMBER = 6;
    private volatile java.lang.Object headPictureUrl_;
    /**
     * <pre>
     * 头像地址
     * </pre>
     *
     * <code>optional string headPictureUrl = 6;</code>
     */
    public boolean hasHeadPictureUrl() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 头像地址
     * </pre>
     *
     * <code>optional string headPictureUrl = 6;</code>
     */
    public java.lang.String getHeadPictureUrl() {
      java.lang.Object ref = headPictureUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headPictureUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 头像地址
     * </pre>
     *
     * <code>optional string headPictureUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHeadPictureUrlBytes() {
      java.lang.Object ref = headPictureUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headPictureUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 7;
    private volatile java.lang.Object gender_;
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional string gender = 7;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional string gender = 7;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gender_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional string gender = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBaseResp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBaseResp().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getBaseResp());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, sessionId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, loginIp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nickName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, headPictureUrl_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gender_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseResp());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, sessionId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, loginIp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nickName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, headPictureUrl_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, gender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp)) {
        return super.equals(obj);
      }
      com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp other = (com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp) obj;

      boolean result = true;
      result = result && (hasBaseResp() == other.hasBaseResp());
      if (hasBaseResp()) {
        result = result && getBaseResp()
            .equals(other.getBaseResp());
      }
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && (getUid()
            == other.getUid());
      }
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && (getSessionId()
            == other.getSessionId());
      }
      result = result && (hasLoginIp() == other.hasLoginIp());
      if (hasLoginIp()) {
        result = result && getLoginIp()
            .equals(other.getLoginIp());
      }
      result = result && (hasNickName() == other.hasNickName());
      if (hasNickName()) {
        result = result && getNickName()
            .equals(other.getNickName());
      }
      result = result && (hasHeadPictureUrl() == other.hasHeadPictureUrl());
      if (hasHeadPictureUrl()) {
        result = result && getHeadPictureUrl()
            .equals(other.getHeadPictureUrl());
      }
      result = result && (hasGender() == other.hasGender());
      if (hasGender()) {
        result = result && getGender()
            .equals(other.getGender());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseResp()) {
        hash = (37 * hash) + BASERESP_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResp().hashCode();
      }
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUid());
      }
      if (hasSessionId()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSessionId());
      }
      if (hasLoginIp()) {
        hash = (37 * hash) + LOGINIP_FIELD_NUMBER;
        hash = (53 * hash) + getLoginIp().hashCode();
      }
      if (hasNickName()) {
        hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
        hash = (53 * hash) + getNickName().hashCode();
      }
      if (hasHeadPictureUrl()) {
        hash = (37 * hash) + HEADPICTUREURL_FIELD_NUMBER;
        hash = (53 * hash) + getHeadPictureUrl().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + getGender().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.app.user.UserSignInResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.app.user.UserSignInResp)
        com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.efun.game.protobuf.app.user.UserSingInRespProto.internal_static_protobuf_app_user_UserSignInResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.efun.game.protobuf.app.user.UserSingInRespProto.internal_static_protobuf_app_user_UserSignInResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.class, com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.Builder.class);
      }

      // Construct using com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBaseRespFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
        } else {
          baseRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        loginIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        headPictureUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        gender_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.efun.game.protobuf.app.user.UserSingInRespProto.internal_static_protobuf_app_user_UserSignInResp_descriptor;
      }

      public com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp getDefaultInstanceForType() {
        return com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.getDefaultInstance();
      }

      public com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp build() {
        com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp buildPartial() {
        com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp result = new com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.loginIp_ = loginIp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.headPictureUrl_ = headPictureUrl_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gender_ = gender_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp) {
          return mergeFrom((com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp other) {
        if (other == com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp.getDefaultInstance()) return this;
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasLoginIp()) {
          bitField0_ |= 0x00000008;
          loginIp_ = other.loginIp_;
          onChanged();
        }
        if (other.hasNickName()) {
          bitField0_ |= 0x00000010;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasHeadPictureUrl()) {
          bitField0_ |= 0x00000020;
          headPictureUrl_ = other.headPictureUrl_;
          onChanged();
        }
        if (other.hasGender()) {
          bitField0_ |= 0x00000040;
          gender_ = other.gender_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBaseResp()) {
          return false;
        }
        if (!getBaseResp().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.efun.game.protobuf.app.BaseRespProto.BaseResp baseResp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.efun.game.protobuf.app.BaseRespProto.BaseResp, com.efun.game.protobuf.app.BaseRespProto.BaseResp.Builder, com.efun.game.protobuf.app.BaseRespProto.BaseRespOrBuilder> baseRespBuilder_;
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public boolean hasBaseResp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public com.efun.game.protobuf.app.BaseRespProto.BaseResp getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_ == null ? com.efun.game.protobuf.app.BaseRespProto.BaseResp.getDefaultInstance() : baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public Builder setBaseResp(com.efun.game.protobuf.app.BaseRespProto.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public Builder setBaseResp(
          com.efun.game.protobuf.app.BaseRespProto.BaseResp.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public Builder mergeBaseResp(com.efun.game.protobuf.app.BaseRespProto.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              baseResp_ != null &&
              baseResp_ != com.efun.game.protobuf.app.BaseRespProto.BaseResp.getDefaultInstance()) {
            baseResp_ =
              com.efun.game.protobuf.app.BaseRespProto.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
          onChanged();
        } else {
          baseRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public com.efun.game.protobuf.app.BaseRespProto.BaseResp.Builder getBaseRespBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      public com.efun.game.protobuf.app.BaseRespProto.BaseRespOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_ == null ?
              com.efun.game.protobuf.app.BaseRespProto.BaseResp.getDefaultInstance() : baseResp_;
        }
      }
      /**
       * <pre>
       * 处理结果
       * </pre>
       *
       * <code>required .protobuf.app.BaseResp baseResp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.efun.game.protobuf.app.BaseRespProto.BaseResp, com.efun.game.protobuf.app.BaseRespProto.BaseResp.Builder, com.efun.game.protobuf.app.BaseRespProto.BaseRespOrBuilder> 
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.efun.game.protobuf.app.BaseRespProto.BaseResp, com.efun.game.protobuf.app.BaseRespProto.BaseResp.Builder, com.efun.game.protobuf.app.BaseRespProto.BaseRespOrBuilder>(
                  getBaseResp(),
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }

      private long uid_ ;
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>optional fixed64 uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>optional fixed64 uid = 2;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>optional fixed64 uid = 2;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>optional fixed64 uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>optional fixed64 sessionId = 3;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional fixed64 sessionId = 3;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional fixed64 sessionId = 3;</code>
       */
      public Builder setSessionId(long value) {
        bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object loginIp_ = "";
      /**
       * <pre>
       * 登录ip
       * </pre>
       *
       * <code>optional string loginIp = 4;</code>
       */
      public boolean hasLoginIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 登录ip
       * </pre>
       *
       * <code>optional string loginIp = 4;</code>
       */
      public java.lang.String getLoginIp() {
        java.lang.Object ref = loginIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 登录ip
       * </pre>
       *
       * <code>optional string loginIp = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoginIpBytes() {
        java.lang.Object ref = loginIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 登录ip
       * </pre>
       *
       * <code>optional string loginIp = 4;</code>
       */
      public Builder setLoginIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        loginIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 登录ip
       * </pre>
       *
       * <code>optional string loginIp = 4;</code>
       */
      public Builder clearLoginIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loginIp_ = getDefaultInstance().getLoginIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 登录ip
       * </pre>
       *
       * <code>optional string loginIp = 4;</code>
       */
      public Builder setLoginIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        loginIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>optional string nickName = 5;</code>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>optional string nickName = 5;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>optional string nickName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>optional string nickName = 5;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>optional string nickName = 5;</code>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>optional string nickName = 5;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headPictureUrl_ = "";
      /**
       * <pre>
       * 头像地址
       * </pre>
       *
       * <code>optional string headPictureUrl = 6;</code>
       */
      public boolean hasHeadPictureUrl() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 头像地址
       * </pre>
       *
       * <code>optional string headPictureUrl = 6;</code>
       */
      public java.lang.String getHeadPictureUrl() {
        java.lang.Object ref = headPictureUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headPictureUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 头像地址
       * </pre>
       *
       * <code>optional string headPictureUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHeadPictureUrlBytes() {
        java.lang.Object ref = headPictureUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headPictureUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 头像地址
       * </pre>
       *
       * <code>optional string headPictureUrl = 6;</code>
       */
      public Builder setHeadPictureUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        headPictureUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像地址
       * </pre>
       *
       * <code>optional string headPictureUrl = 6;</code>
       */
      public Builder clearHeadPictureUrl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        headPictureUrl_ = getDefaultInstance().getHeadPictureUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像地址
       * </pre>
       *
       * <code>optional string headPictureUrl = 6;</code>
       */
      public Builder setHeadPictureUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        headPictureUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional string gender = 7;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional string gender = 7;</code>
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional string gender = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional string gender = 7;</code>
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional string gender = 7;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional string gender = 7;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        gender_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.app.user.UserSignInResp)
    }

    // @@protoc_insertion_point(class_scope:protobuf.app.user.UserSignInResp)
    private static final com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp();
    }

    public static com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserSignInResp>
        PARSER = new com.google.protobuf.AbstractParser<UserSignInResp>() {
      public UserSignInResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserSignInResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserSignInResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserSignInResp> getParserForType() {
      return PARSER;
    }

    public com.efun.game.protobuf.app.user.UserSingInRespProto.UserSignInResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_app_user_UserSignInResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_app_user_UserSignInResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031user/UserSignInResp.proto\022\021protobuf.ap" +
      "p.user\032\016BaseResp.proto\"\245\001\n\016UserSignInRes" +
      "p\022(\n\010baseResp\030\001 \002(\0132\026.protobuf.app.BaseR" +
      "esp\022\013\n\003uid\030\002 \001(\006\022\021\n\tsessionId\030\003 \001(\006\022\017\n\007l" +
      "oginIp\030\004 \001(\t\022\020\n\010nickName\030\005 \001(\t\022\026\n\016headPi" +
      "ctureUrl\030\006 \001(\t\022\016\n\006gender\030\007 \001(\tB6\n\037com.ef" +
      "un.game.protobuf.app.userB\023UserSingInRes" +
      "pProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.efun.game.protobuf.app.BaseRespProto.getDescriptor(),
        }, assigner);
    internal_static_protobuf_app_user_UserSignInResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_app_user_UserSignInResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_app_user_UserSignInResp_descriptor,
        new java.lang.String[] { "BaseResp", "Uid", "SessionId", "LoginIp", "NickName", "HeadPictureUrl", "Gender", });
    com.efun.game.protobuf.app.BaseRespProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
