// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/UpdateUserSignInStatusReq.proto

package com.efun.game.protobuf.app.message;

public final class UpdateUserSignInStatusReqProto {
  private UpdateUserSignInStatusReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateUserSignInStatusReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.app.message.UpdateUserSignInStatusReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * uid
     * </pre>
     *
     * <code>required fixed64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <pre>
     * uid
     * </pre>
     *
     * <code>required fixed64 uid = 1;</code>
     */
    long getUid();

    /**
     * <pre>
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 2;</code>
     */
    boolean hasAppType();
    /**
     * <pre>
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 2;</code>
     */
    com.efun.game.protobuf.app.EnumsProto.AppType getAppType();

    /**
     * <pre>
     * 登录状态
     * </pre>
     *
     * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
     */
    boolean hasSignInStatus();
    /**
     * <pre>
     * 登录状态
     * </pre>
     *
     * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
     */
    com.efun.game.protobuf.app.EnumsProto.UserSignInStatus getSignInStatus();
  }
  /**
   * Protobuf type {@code protobuf.app.message.UpdateUserSignInStatusReq}
   */
  public  static final class UpdateUserSignInStatusReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.app.message.UpdateUserSignInStatusReq)
      UpdateUserSignInStatusReqOrBuilder {
    // Use UpdateUserSignInStatusReq.newBuilder() to construct.
    private UpdateUserSignInStatusReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateUserSignInStatusReq() {
      uid_ = 0L;
      appType_ = 0;
      signInStatus_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateUserSignInStatusReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              uid_ = input.readFixed64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.app.EnumsProto.AppType value = com.efun.game.protobuf.app.EnumsProto.AppType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                appType_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.efun.game.protobuf.app.EnumsProto.UserSignInStatus value = com.efun.game.protobuf.app.EnumsProto.UserSignInStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                signInStatus_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.internal_static_protobuf_app_message_UpdateUserSignInStatusReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.internal_static_protobuf_app_message_UpdateUserSignInStatusReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.class, com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     * uid
     * </pre>
     *
     * <code>required fixed64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * uid
     * </pre>
     *
     * <code>required fixed64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int APPTYPE_FIELD_NUMBER = 2;
    private int appType_;
    /**
     * <pre>
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 2;</code>
     */
    public boolean hasAppType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>required .protobuf.app.AppType appType = 2;</code>
     */
    public com.efun.game.protobuf.app.EnumsProto.AppType getAppType() {
      com.efun.game.protobuf.app.EnumsProto.AppType result = com.efun.game.protobuf.app.EnumsProto.AppType.valueOf(appType_);
      return result == null ? com.efun.game.protobuf.app.EnumsProto.AppType.APP_UNKNOWN : result;
    }

    public static final int SIGNINSTATUS_FIELD_NUMBER = 3;
    private int signInStatus_;
    /**
     * <pre>
     * 登录状态
     * </pre>
     *
     * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
     */
    public boolean hasSignInStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 登录状态
     * </pre>
     *
     * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
     */
    public com.efun.game.protobuf.app.EnumsProto.UserSignInStatus getSignInStatus() {
      com.efun.game.protobuf.app.EnumsProto.UserSignInStatus result = com.efun.game.protobuf.app.EnumsProto.UserSignInStatus.valueOf(signInStatus_);
      return result == null ? com.efun.game.protobuf.app.EnumsProto.UserSignInStatus.OFF_LINE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignInStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, appType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, signInStatus_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, appType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, signInStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq)) {
        return super.equals(obj);
      }
      com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq other = (com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq) obj;

      boolean result = true;
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && (getUid()
            == other.getUid());
      }
      result = result && (hasAppType() == other.hasAppType());
      if (hasAppType()) {
        result = result && appType_ == other.appType_;
      }
      result = result && (hasSignInStatus() == other.hasSignInStatus());
      if (hasSignInStatus()) {
        result = result && signInStatus_ == other.signInStatus_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUid());
      }
      if (hasAppType()) {
        hash = (37 * hash) + APPTYPE_FIELD_NUMBER;
        hash = (53 * hash) + appType_;
      }
      if (hasSignInStatus()) {
        hash = (37 * hash) + SIGNINSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + signInStatus_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.app.message.UpdateUserSignInStatusReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.app.message.UpdateUserSignInStatusReq)
        com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.internal_static_protobuf_app_message_UpdateUserSignInStatusReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.internal_static_protobuf_app_message_UpdateUserSignInStatusReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.class, com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.Builder.class);
      }

      // Construct using com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        appType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        signInStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.internal_static_protobuf_app_message_UpdateUserSignInStatusReq_descriptor;
      }

      public com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq getDefaultInstanceForType() {
        return com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.getDefaultInstance();
      }

      public com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq build() {
        com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq buildPartial() {
        com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq result = new com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appType_ = appType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.signInStatus_ = signInStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq) {
          return mergeFrom((com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq other) {
        if (other == com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasAppType()) {
          setAppType(other.getAppType());
        }
        if (other.hasSignInStatus()) {
          setSignInStatus(other.getSignInStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasAppType()) {
          return false;
        }
        if (!hasSignInStatus()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>required fixed64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>required fixed64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>required fixed64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uid
       * </pre>
       *
       * <code>required fixed64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private int appType_ = 0;
      /**
       * <pre>
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 2;</code>
       */
      public boolean hasAppType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 2;</code>
       */
      public com.efun.game.protobuf.app.EnumsProto.AppType getAppType() {
        com.efun.game.protobuf.app.EnumsProto.AppType result = com.efun.game.protobuf.app.EnumsProto.AppType.valueOf(appType_);
        return result == null ? com.efun.game.protobuf.app.EnumsProto.AppType.APP_UNKNOWN : result;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 2;</code>
       */
      public Builder setAppType(com.efun.game.protobuf.app.EnumsProto.AppType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        appType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required .protobuf.app.AppType appType = 2;</code>
       */
      public Builder clearAppType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appType_ = 0;
        onChanged();
        return this;
      }

      private int signInStatus_ = 0;
      /**
       * <pre>
       * 登录状态
       * </pre>
       *
       * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
       */
      public boolean hasSignInStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 登录状态
       * </pre>
       *
       * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
       */
      public com.efun.game.protobuf.app.EnumsProto.UserSignInStatus getSignInStatus() {
        com.efun.game.protobuf.app.EnumsProto.UserSignInStatus result = com.efun.game.protobuf.app.EnumsProto.UserSignInStatus.valueOf(signInStatus_);
        return result == null ? com.efun.game.protobuf.app.EnumsProto.UserSignInStatus.OFF_LINE : result;
      }
      /**
       * <pre>
       * 登录状态
       * </pre>
       *
       * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
       */
      public Builder setSignInStatus(com.efun.game.protobuf.app.EnumsProto.UserSignInStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        signInStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 登录状态
       * </pre>
       *
       * <code>required .protobuf.app.UserSignInStatus signInStatus = 3;</code>
       */
      public Builder clearSignInStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        signInStatus_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.app.message.UpdateUserSignInStatusReq)
    }

    // @@protoc_insertion_point(class_scope:protobuf.app.message.UpdateUserSignInStatusReq)
    private static final com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq();
    }

    public static com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UpdateUserSignInStatusReq>
        PARSER = new com.google.protobuf.AbstractParser<UpdateUserSignInStatusReq>() {
      public UpdateUserSignInStatusReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateUserSignInStatusReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateUserSignInStatusReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateUserSignInStatusReq> getParserForType() {
      return PARSER;
    }

    public com.efun.game.protobuf.app.message.UpdateUserSignInStatusReqProto.UpdateUserSignInStatusReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_app_message_UpdateUserSignInStatusReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_app_message_UpdateUserSignInStatusReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'message/UpdateUserSignInStatusReq.prot" +
      "o\022\024protobuf.app.message\032\013Enums.proto\"\206\001\n" +
      "\031UpdateUserSignInStatusReq\022\013\n\003uid\030\001 \002(\006\022" +
      "&\n\007appType\030\002 \002(\0162\025.protobuf.app.AppType\022" +
      "4\n\014signInStatus\030\003 \002(\0162\036.protobuf.app.Use" +
      "rSignInStatusBD\n\"com.efun.game.protobuf." +
      "app.messageB\036UpdateUserSignInStatusReqPr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.efun.game.protobuf.app.EnumsProto.getDescriptor(),
        }, assigner);
    internal_static_protobuf_app_message_UpdateUserSignInStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_app_message_UpdateUserSignInStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_app_message_UpdateUserSignInStatusReq_descriptor,
        new java.lang.String[] { "Uid", "AppType", "SignInStatus", });
    com.efun.game.protobuf.app.EnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
