// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package com.efun.game.protobuf.app;

public final class EnumsProto {
  private EnumsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protobuf.app.UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 用户类型: 1-用户名; 2-手机号; 3-身份证; 4-邮箱
     * </pre>
     *
     * <code>USER_NAME = 1;</code>
     */
    USER_NAME(1),
    /**
     * <pre>
     * 手机号
     * </pre>
     *
     * <code>USER_MOBILE = 2;</code>
     */
    USER_MOBILE(2),
    /**
     * <pre>
     * 身份证
     * </pre>
     *
     * <code>USER_ID_CARD = 3;</code>
     */
    USER_ID_CARD(3),
    /**
     * <pre>
     * 邮箱
     * </pre>
     *
     * <code>USER_EMAIL = 4;</code>
     */
    USER_EMAIL(4),
    ;

    /**
     * <pre>
     * 用户类型: 1-用户名; 2-手机号; 3-身份证; 4-邮箱
     * </pre>
     *
     * <code>USER_NAME = 1;</code>
     */
    public static final int USER_NAME_VALUE = 1;
    /**
     * <pre>
     * 手机号
     * </pre>
     *
     * <code>USER_MOBILE = 2;</code>
     */
    public static final int USER_MOBILE_VALUE = 2;
    /**
     * <pre>
     * 身份证
     * </pre>
     *
     * <code>USER_ID_CARD = 3;</code>
     */
    public static final int USER_ID_CARD_VALUE = 3;
    /**
     * <pre>
     * 邮箱
     * </pre>
     *
     * <code>USER_EMAIL = 4;</code>
     */
    public static final int USER_EMAIL_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserType valueOf(int value) {
      return forNumber(value);
    }

    public static UserType forNumber(int value) {
      switch (value) {
        case 1: return USER_NAME;
        case 2: return USER_MOBILE;
        case 3: return USER_ID_CARD;
        case 4: return USER_EMAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.efun.game.protobuf.app.EnumsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.app.UserType)
  }

  /**
   * Protobuf enum {@code protobuf.app.AppType}
   */
  public enum AppType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 0-未知; 1-Web; 2-IOS; 3-Andriod
     * </pre>
     *
     * <code>APP_UNKNOWN = 0;</code>
     */
    APP_UNKNOWN(0),
    /**
     * <pre>
     * Web
     * </pre>
     *
     * <code>APP_WEB = 1;</code>
     */
    APP_WEB(1),
    /**
     * <pre>
     * IOS
     * </pre>
     *
     * <code>APP_IOS = 2;</code>
     */
    APP_IOS(2),
    /**
     * <pre>
     * Andriod
     * </pre>
     *
     * <code>APP_ANDRIOD = 3;</code>
     */
    APP_ANDRIOD(3),
    ;

    /**
     * <pre>
     * 0-未知; 1-Web; 2-IOS; 3-Andriod
     * </pre>
     *
     * <code>APP_UNKNOWN = 0;</code>
     */
    public static final int APP_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Web
     * </pre>
     *
     * <code>APP_WEB = 1;</code>
     */
    public static final int APP_WEB_VALUE = 1;
    /**
     * <pre>
     * IOS
     * </pre>
     *
     * <code>APP_IOS = 2;</code>
     */
    public static final int APP_IOS_VALUE = 2;
    /**
     * <pre>
     * Andriod
     * </pre>
     *
     * <code>APP_ANDRIOD = 3;</code>
     */
    public static final int APP_ANDRIOD_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AppType valueOf(int value) {
      return forNumber(value);
    }

    public static AppType forNumber(int value) {
      switch (value) {
        case 0: return APP_UNKNOWN;
        case 1: return APP_WEB;
        case 2: return APP_IOS;
        case 3: return APP_ANDRIOD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AppType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AppType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AppType>() {
            public AppType findValueByNumber(int number) {
              return AppType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.efun.game.protobuf.app.EnumsProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final AppType[] VALUES = values();

    public static AppType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AppType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.app.AppType)
  }

  /**
   * Protobuf enum {@code protobuf.app.UserSignInStatus}
   */
  public enum UserSignInStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 0-离线; 1-上线
     * </pre>
     *
     * <code>OFF_LINE = 0;</code>
     */
    OFF_LINE(0),
    /**
     * <pre>
     * 上线
     * </pre>
     *
     * <code>ON_LINE = 1;</code>
     */
    ON_LINE(1),
    ;

    /**
     * <pre>
     * 0-离线; 1-上线
     * </pre>
     *
     * <code>OFF_LINE = 0;</code>
     */
    public static final int OFF_LINE_VALUE = 0;
    /**
     * <pre>
     * 上线
     * </pre>
     *
     * <code>ON_LINE = 1;</code>
     */
    public static final int ON_LINE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserSignInStatus valueOf(int value) {
      return forNumber(value);
    }

    public static UserSignInStatus forNumber(int value) {
      switch (value) {
        case 0: return OFF_LINE;
        case 1: return ON_LINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserSignInStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserSignInStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserSignInStatus>() {
            public UserSignInStatus findValueByNumber(int number) {
              return UserSignInStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.efun.game.protobuf.app.EnumsProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final UserSignInStatus[] VALUES = values();

    public static UserSignInStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserSignInStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.app.UserSignInStatus)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Enums.proto\022\014protobuf.app*L\n\010UserType\022" +
      "\r\n\tUSER_NAME\020\001\022\017\n\013USER_MOBILE\020\002\022\020\n\014USER_" +
      "ID_CARD\020\003\022\016\n\nUSER_EMAIL\020\004*E\n\007AppType\022\017\n\013" +
      "APP_UNKNOWN\020\000\022\013\n\007APP_WEB\020\001\022\013\n\007APP_IOS\020\002\022" +
      "\017\n\013APP_ANDRIOD\020\003*-\n\020UserSignInStatus\022\014\n\010" +
      "OFF_LINE\020\000\022\013\n\007ON_LINE\020\001B(\n\032com.efun.game" +
      ".protobuf.appB\nEnumsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
